# Generated by Django 3.2 on 2021-04-15 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_tasks_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tasks',
            table=None,
        ),
    ]
